### PR TITLE
Added feature to allow default extensions

### PR DESCRIPTION
**Pull request by dploeger**
This PR adds a feature to allow a default extension for files, that have no extension set after filtered.

The need for this feature came along, because we wanted to host the generated documentation in another generated documentation and that didn't work without the .html extension for HTML files in links.

This PR adds an option called "defaultExt" which can be set to e.g. ".html" and will set this extension in the _href data for pages, that have no extension (e.g. Markdown-sources). Generated Index files are left out.

### CODE REVIEW

**Comment by dploeger** [comment]
I added a test for it. However, the test suite doesn't succeed, but I believe that's not due to my changes.

**Comment by dploeger** [comment]
@jldec Could this be merged?

**Comment by jldec** [comment]
Hi @dploeger thanks for the inquiry - sorry for the delays - this projects has had to take a back seat for a little while. Your PR suggestion looks reasonable - the only only change i might ask for the `defaultExt` option to live on the source intead of the root of the opts object.

I'm in the process of doing a general housekeeping upgrade of the modules in pub-server/pub-generator - hopefully that will allow me to fix the failing test and then merge your change.

**Comment by dploeger** [comment]
Thank you.

I've integrated the additional change you asked for.

**Comment by jldec** [comment]
Setting `source.defaultExt` to `.htm` or `.html` will create hrefs with one of those extensions, instead of no extension.

The same is also possible by setting an explicit extension for the href in the markdown file frontmatter.

See pub-server v2.11.3 or pub-generator v.4.3.5

**Pull request closed without merging**
